### ISSUE TITLE
Driver using script defined in library rather than that defined in the driver

### ISSUE THREAD

**Issue by phreed** [phreed/pixi-build-example#1]
Why does removing 
```toml
[project]
scripts = { rich-example-main = "python_rich_mgr:main" } 
```
From here:
https://github.com/phreed/pixi-build-example/blob/02-multi-compose/pkgs/python_rich/pyproject.toml#L5

Cause `pixi run start` to stop working?
It seems like the definition found here:
https://github.com/phreed/pixi-build-example/blob/02-multi-compose/pyproject.toml#L5

Should be sufficient.
